//! Unbounded local fuzz driver.
//!
//! Runs until interrupted (or until `--iterations` is reached), feeding
//! generated byte sequences into the same fuzz bodies the `cargo-fuzz` targets
//! use. This runs on stable with no external dependencies, which is what makes
//! it usable without installing a fuzzing toolchain.
//!
//! It is *not* coverage-guided: a `cargo-fuzz` run will reach cases this driver
//! will not. Treat this as the always-available baseline and libFuzzer as the
//! deeper sweep. See `fuzz/README.md`.
//!
//! Never part of CI: the crate is excluded from the workspace on purpose.

use std::time::Instant;

/// xorshift64*, so a failing run can be reproduced from its printed seed
/// without pulling in an RNG dependency.
struct Rng(u64);

impl Rng {
    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_f491_4f6c_dd1d)
    }

    fn fill(&mut self, buffer: &mut Vec<u8>, len: usize) {
        buffer.clear();
        while buffer.len() < len {
            buffer.extend_from_slice(&self.next_u64().to_le_bytes());
        }
        buffer.truncate(len);
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut seed = 0x9e37_79b9_7f4a_7c15_u64;
    let mut iterations: Option<u64> = None;
    let mut index = 1;
    while index < args.len() {
        match args[index].as_str() {
            "--seed" => {
                index += 1;
                seed = args.get(index).and_then(|v| v.parse().ok()).unwrap_or(seed);
            }
            "--iterations" => {
                index += 1;
                iterations = args.get(index).and_then(|v| v.parse().ok());
            }
            other => {
                eprintln!("unknown argument: {other}");
                eprintln!("usage: sunmao_fuzz [--seed <u64>] [--iterations <n>]");
                std::process::exit(2);
            }
        }
        index += 1;
    }

    println!("sunmao_fuzz: seed={seed} iterations={iterations:?} (Ctrl-C to stop)");
    let mut rng = Rng(seed | 1);
    let mut buffer = Vec::new();
    let started = Instant::now();
    let mut count = 0u64;

    loop {
        if let Some(limit) = iterations {
            if count >= limit {
                break;
            }
        }

        // Mix wholly random bytes with blobs that start from a valid-looking
        // header, so the decoder is exercised past its first rejection as well
        // as at it.
        let len = (rng.next_u64() % 512) as usize;
        rng.fill(&mut buffer, len);
        match rng.next_u64() % 4 {
            0 => {
                buffer.splice(0..0, *b"SMCLPRM\0");
            }
            1 => {
                buffer.splice(0..0, *b"SMV3PRM\0");
            }
            _ => {}
        }

        sunmao_fuzz::fuzz_clap_state_load(&buffer);
        sunmao_fuzz::fuzz_vst3_state_load(&buffer);

        count += 1;
        if count % 10_000 == 0 {
            println!(
                "{count} cases in {:.1}s ({:.0}/s)",
                started.elapsed().as_secs_f64(),
                count as f64 / started.elapsed().as_secs_f64()
            );
        }
    }

    println!("sunmao_fuzz: {count} cases, no crash");
}
