use crate::ext::{AudioPortInfo, NotePortInfo, ParameterInfo, RenderMode, VoiceInfo};
use crate::process::ProcessContext;
use clap_sys::events::{
    CLAP_CORE_EVENT_SPACE_ID, CLAP_EVENT_PARAM_GESTURE_BEGIN, CLAP_EVENT_PARAM_GESTURE_END,
    CLAP_EVENT_PARAM_VALUE, clap_event_header_t, clap_event_param_gesture_t,
    clap_event_param_value_t, clap_output_events_t,
};
use clap_sys::ext::gui::{CLAP_EXT_GUI, clap_host_gui_t};
use clap_sys::ext::params::{CLAP_EXT_PARAMS, clap_host_params_t};
use clap_sys::host::clap_host_t;
use clap_sys::plugin::clap_plugin_descriptor_t;
use rtrb::{Consumer, Producer, RingBuffer};
use std::cell::UnsafeCell;
use std::ffi::{CString, c_char};
use std::sync::{Arc, Mutex};

// Re-export commonly used types
pub use clap_sys::process::CLAP_PROCESS_CONTINUE;
pub use clap_sys::version::CLAP_VERSION;

/// Metadata published in the CLAP plugin descriptor.
///
/// Fields are ordinary Rust strings. The export macros create and retain the
/// NUL-terminated copies required by the CLAP ABI.
#[derive(Clone, Copy, Debug)]
pub struct PluginInfo {
    pub id: &'static str,
    pub name: &'static str,
    pub vendor: &'static str,
    pub url: &'static str,
    pub manual_url: &'static str,
    pub support_url: &'static str,
    pub version: &'static str,
    pub description: &'static str,
}

/// Owned backing storage for a CLAP plugin descriptor generated by the export macros.
#[doc(hidden)]
pub struct OwnedPluginDescriptor {
    descriptor: clap_plugin_descriptor_t,
    _id: CString,
    _name: CString,
    _vendor: CString,
    _url: CString,
    _manual_url: CString,
    _support_url: CString,
    _version: CString,
    _description: CString,
}

unsafe impl Send for OwnedPluginDescriptor {}
unsafe impl Sync for OwnedPluginDescriptor {}

impl OwnedPluginDescriptor {
    /// Builds an ABI descriptor while retaining all of its string storage.
    ///
    /// A single trailing NUL is accepted for compatibility with older
    /// `clap_rs` callers. Any other NUL byte rejects the descriptor.
    #[doc(hidden)]
    pub fn new(info: &PluginInfo, features: *const *const c_char) -> Result<Self, &'static str> {
        fn c_string(field: &'static str, value: &str) -> Result<CString, &'static str> {
            let value = value.strip_suffix('\0').unwrap_or(value);
            CString::new(value).map_err(|_| field)
        }

        let id = c_string("id", info.id)?;
        let name = c_string("name", info.name)?;
        let vendor = c_string("vendor", info.vendor)?;
        let url = c_string("url", info.url)?;
        let manual_url = c_string("manual_url", info.manual_url)?;
        let support_url = c_string("support_url", info.support_url)?;
        let version = c_string("version", info.version)?;
        let description = c_string("description", info.description)?;

        let descriptor = clap_plugin_descriptor_t {
            clap_version: CLAP_VERSION,
            id: id.as_ptr(),
            name: name.as_ptr(),
            vendor: vendor.as_ptr(),
            url: url.as_ptr(),
            manual_url: manual_url.as_ptr(),
            support_url: support_url.as_ptr(),
            version: version.as_ptr(),
            description: description.as_ptr(),
            features,
        };

        Ok(Self {
            descriptor,
            _id: id,
            _name: name,
            _vendor: vendor,
            _url: url,
            _manual_url: manual_url,
            _support_url: support_url,
            _version: version,
            _description: description,
        })
    }

    #[doc(hidden)]
    pub fn as_raw(&self) -> &clap_plugin_descriptor_t {
        &self.descriptor
    }
}

/// State exclusively owned by CLAP's audio thread while the plugin is active.
///
/// Implementations should share host-visible parameters with their [`Plugin`]
/// controller through lock-free storage such as atomics. The CLAP host
/// serializes these callbacks on the audio thread.
pub trait AudioProcessor: Send + 'static {
    fn start_processing(&mut self) -> bool {
        true
    }

    fn stop_processing(&mut self) {}

    fn reset(&mut self) {}

    fn process(&mut self, process: ProcessContext) -> clap_sys::process::clap_process_status;

    /// Applies parameter changes delivered by `params.flush` while active.
    /// Sample-accurate events in [`ProcessContext`] remain ordered and should
    /// be consumed by [`AudioProcessor::process`].
    fn set_parameter(&mut self, id: u32, value: f64);
}

impl AudioProcessor for () {
    fn process(&mut self, _process: ProcessContext) -> clap_sys::process::clap_process_status {
        clap_sys::process::CLAP_PROCESS_CONTINUE
    }

    fn set_parameter(&mut self, _id: u32, _value: f64) {}
}

/// Main-thread controller and factory for a CLAP plugin instance.
///
/// Audio processing state must live in [`Plugin::AudioProcessor`], not in this
/// controller. CLAP permits main-thread extension and GUI callbacks to run
/// concurrently with audio processing.
pub trait Plugin: Sized {
    type AudioProcessor: AudioProcessor;

    fn new(host: HostHandle) -> Self;

    // Lifecycle
    fn init(&mut self) -> bool {
        true
    }
    fn activate(
        &mut self,
        sample_rate: f64,
        min_frames: u32,
        max_frames: u32,
    ) -> Option<Self::AudioProcessor>;

    /// Receives the audio-thread state after processing has stopped.
    fn deactivate(&mut self, _processor: Self::AudioProcessor) {}

    // Parameters
    fn declare_parameters(&self) -> Vec<ParameterInfo> {
        Vec::new()
    }
    fn get_parameter(&self, id: u32) -> f64;
    fn set_parameter(&mut self, id: u32, value: f64);

    // Ports
    fn audio_ports_config(&self) -> Vec<AudioPortInfo> {
        Vec::new()
    }
    fn note_ports_config(&self) -> Vec<NotePortInfo> {
        Vec::new()
    }

    // Audio port activation (`clap.audio-ports-activation/2`). The wrapper
    // validates the port index against `audio_ports_config` before forwarding,
    // so implementations only see declared ports. `sample_size` is the host's
    // sample width in bits (32/64) or 0 when unspecified.
    fn set_audio_port_active(
        &mut self,
        _is_input: bool,
        _port_index: u32,
        _is_active: bool,
        _sample_size: u32,
    ) -> bool {
        true
    }

    // Host-selectable port layouts (`clap.audio-ports-config`). Empty (the
    // default) means the plugin has one fixed layout and the extension is not
    // exposed at all.
    fn audio_ports_configs(&self) -> Vec<crate::ext::audio_ports_config::AudioPortsConfig> {
        Vec::new()
    }

    // Id of the layout currently in force, or `CLAP_INVALID_ID` when the
    // plugin does not publish configurations.
    fn current_audio_ports_config_id(&self) -> u32 {
        clap_sys::id::CLAP_INVALID_ID
    }

    // Called when the host selects a published layout. The wrapper rejects
    // unpublished ids first, so this only ever sees an id from
    // `audio_ports_configs`. Returning `false` refuses the switch and keeps
    // the previous layout. On success `audio_ports_config` must report the new
    // layout.
    fn select_audio_ports_config(&mut self, _config_id: u32) -> bool {
        false
    }

    // Whether ports may be (de)activated while processing. Off by default:
    // hosts must deactivate the plugin first, which keeps the callback on the
    // main thread.
    fn can_activate_ports_while_processing(&self) -> bool {
        false
    }

    // Version stamped into saved state. A blob written by an older build is
    // accepted and `state_loaded` reports its version; a newer one is refused
    // because this build cannot know how to read it.
    const STATE_VERSION: u32 = 1;

    // Called after a state blob has been applied, with the version it was
    // written by. Only called when that version is older than
    // `STATE_VERSION` — an identical version needs no migration.
    fn state_loaded(&mut self, _from_version: u32) {}

    // Latency (samples of processing delay)
    fn latency(&self) -> u32 {
        0
    }

    // Tail length cached at serialized controller transitions. CLAP may query
    // the published cache from either thread. Dynamic audio-thread changes
    // require lock-free shared state plus a main-thread refresh/host notice.
    fn tail(&self) -> u32 {
        0
    }

    // Voice information queried on the main thread. Dynamic audio-thread state
    // must be published through lock-free shared storage.
    fn voice_info(&self) -> Option<VoiceInfo> {
        None
    }

    // Render mode (realtime vs offline)
    fn has_hard_realtime_requirement(&self) -> bool {
        false
    }
    fn set_render_mode(&mut self, _mode: RenderMode) -> bool {
        true
    }
}

#[derive(Clone)]
pub struct HostHandle {
    inner: Arc<HostState>,
}

const HOST_PARAMETER_EVENT_CAPACITY: usize = 4096;

#[derive(Clone, Copy)]
enum HostParameterEvent {
    Begin { id: u32 },
    Value { id: u32, value: f64 },
    End { id: u32 },
}

struct HostParameterEvents {
    producer: Mutex<Producer<HostParameterEvent>>,
    consumer: UnsafeCell<Consumer<HostParameterEvent>>,
}

unsafe impl Send for HostParameterEvents {}
unsafe impl Sync for HostParameterEvents {}

struct HostState {
    raw: *const clap_host_t,
    parameter_events: HostParameterEvents,
}

unsafe impl Send for HostState {}
unsafe impl Sync for HostState {}

impl HostState {
    unsafe fn extension<T>(&self, id: &'static str) -> Option<*const T> {
        if self.raw.is_null() {
            return None;
        }
        let get_extension = unsafe { (*self.raw).get_extension }?;
        let extension = unsafe { get_extension(self.raw, id.as_ptr().cast::<c_char>()) };
        (!extension.is_null()).then_some(extension.cast::<T>())
    }

    fn queue_parameter_event(&self, event: HostParameterEvent) -> bool {
        let request_flush = unsafe {
            let Some(params) = self.extension::<clap_host_params_t>(CLAP_EXT_PARAMS) else {
                return false;
            };
            let Some(request_flush) = (*params).request_flush else {
                return false;
            };
            request_flush
        };
        let Ok(mut producer) = self.parameter_events.producer.lock() else {
            return false;
        };
        if producer.push(event).is_err() {
            return false;
        }
        drop(producer);
        unsafe { request_flush(self.raw) };
        true
    }

    unsafe fn flush_parameter_events(&self, output: *const clap_output_events_t) -> usize {
        if output.is_null() {
            return 0;
        }
        let Some(try_push) = (unsafe { (*output).try_push }) else {
            return 0;
        };
        let consumer = unsafe { &mut *self.parameter_events.consumer.get() };
        let mut pushed = 0;
        while let Ok(event) = consumer.peek() {
            let accepted = match *event {
                HostParameterEvent::Begin { id } | HostParameterEvent::End { id } => {
                    let event = clap_event_param_gesture_t {
                        header: clap_event_header_t {
                            size: std::mem::size_of::<clap_event_param_gesture_t>() as u32,
                            time: 0,
                            space_id: CLAP_CORE_EVENT_SPACE_ID,
                            type_: if matches!(*event, HostParameterEvent::Begin { .. }) {
                                CLAP_EVENT_PARAM_GESTURE_BEGIN
                            } else {
                                CLAP_EVENT_PARAM_GESTURE_END
                            },
                            flags: 0,
                        },
                        param_id: id,
                    };
                    unsafe { try_push(output, &event.header) }
                }
                HostParameterEvent::Value { id, value } => {
                    let event = clap_event_param_value_t {
                        header: clap_event_header_t {
                            size: std::mem::size_of::<clap_event_param_value_t>() as u32,
                            time: 0,
                            space_id: CLAP_CORE_EVENT_SPACE_ID,
                            type_: CLAP_EVENT_PARAM_VALUE,
                            flags: 0,
                        },
                        param_id: id,
                        cookie: std::ptr::null_mut(),
                        note_id: -1,
                        port_index: -1,
                        channel: -1,
                        key: -1,
                        value,
                    };
                    unsafe { try_push(output, &event.header) }
                }
            };
            if !accepted {
                break;
            }
            let _ = consumer.pop();
            pushed += 1;
        }
        pushed
    }
}

impl HostHandle {
    pub unsafe fn from_raw(raw: *const clap_host_t) -> Self {
        let (producer, consumer) = RingBuffer::new(HOST_PARAMETER_EVENT_CAPACITY);
        Self {
            inner: Arc::new(HostState {
                raw,
                parameter_events: HostParameterEvents {
                    producer: Mutex::new(producer),
                    consumer: UnsafeCell::new(consumer),
                },
            }),
        }
    }

    /// Queue the beginning of a GUI parameter gesture and request `params.flush`.
    pub fn begin_edit(&self, id: u32) -> bool {
        self.inner
            .queue_parameter_event(HostParameterEvent::Begin { id })
    }

    /// Queue a GUI parameter value and request `params.flush`.
    pub fn perform_edit(&self, id: u32, value: f64) -> bool {
        if !value.is_finite() {
            return false;
        }
        self.inner
            .queue_parameter_event(HostParameterEvent::Value { id, value })
    }

    /// Queue the end of a GUI parameter gesture and request `params.flush`.
    pub fn end_edit(&self, id: u32) -> bool {
        self.inner
            .queue_parameter_event(HostParameterEvent::End { id })
    }

    /// Ask the CLAP host to resize the editor window.
    pub fn request_resize(&self, width: u32, height: u32) -> bool {
        unsafe {
            let Some(gui) = self.inner.extension::<clap_host_gui_t>(CLAP_EXT_GUI) else {
                return false;
            };
            let Some(request_resize) = (*gui).request_resize else {
                return false;
            };
            request_resize(self.inner.raw, width, height)
        }
    }

    pub(crate) unsafe fn flush_parameter_events(
        &self,
        output: *const clap_output_events_t,
    ) -> usize {
        unsafe { self.inner.flush_parameter_events(output) }
    }
}

unsafe impl Send for HostHandle {}
unsafe impl Sync for HostHandle {}

#[doc(hidden)]
#[macro_export]
macro_rules! __export_clap_plugin_impl {
    ($plugin_type:ty, $plugin_info:expr, $features:expr, $entry_type:ident) => {
        mod __clap_rs_impl {
            use super::*;
            use std::ffi::{CStr, c_char, c_void};
            use std::sync::OnceLock;

            struct SyncFactory($crate::clap_sys::factory::plugin_factory::clap_plugin_factory_t);
            unsafe impl Sync for SyncFactory {}

            fn descriptor() -> Option<&'static $crate::clap_sys::plugin::clap_plugin_descriptor_t> {
                static DESCRIPTOR: OnceLock<
                    Result<$crate::plugin::OwnedPluginDescriptor, &'static str>,
                > = OnceLock::new();
                DESCRIPTOR
                    .get_or_init(|| {
                        std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                            $crate::plugin::OwnedPluginDescriptor::new(
                                &$plugin_info,
                                $features.as_ptr(),
                            )
                        }))
                        .unwrap_or(Err("plugin metadata panicked"))
                    })
                    .as_ref()
                    .ok()
                    .map($crate::plugin::OwnedPluginDescriptor::as_raw)
            }

            unsafe extern "C" fn create_plugin(
                _factory: *const $crate::clap_sys::factory::plugin_factory::clap_plugin_factory_t,
                host: *const $crate::clap_sys::host::clap_host_t,
                plugin_id: *const c_char,
            ) -> *const $crate::clap_sys::plugin::clap_plugin_t {
                if plugin_id.is_null() {
                    return std::ptr::null();
                }
                let Some(descriptor) = descriptor() else {
                    return std::ptr::null();
                };
                let id = unsafe { CStr::from_ptr(plugin_id) };
                let target_id = unsafe { CStr::from_ptr(descriptor.id) };

                if id == target_id {
                    return unsafe {
                        $crate::entry::$entry_type::create_plugin::<$plugin_type>(host, descriptor)
                    };
                }
                std::ptr::null()
            }

            static FACTORY: SyncFactory = SyncFactory(
                $crate::clap_sys::factory::plugin_factory::clap_plugin_factory_t {
                    get_plugin_count: Some(get_plugin_count),
                    get_plugin_descriptor: Some(get_plugin_descriptor),
                    create_plugin: Some(create_plugin),
                },
            );

            unsafe extern "C" fn get_plugin_count(
                _factory: *const $crate::clap_sys::factory::plugin_factory::clap_plugin_factory_t,
            ) -> u32 {
                u32::from(descriptor().is_some())
            }
            unsafe extern "C" fn get_plugin_descriptor(
                _factory: *const $crate::clap_sys::factory::plugin_factory::clap_plugin_factory_t,
                index: u32,
            ) -> *const $crate::clap_sys::plugin::clap_plugin_descriptor_t {
                if index != 0 {
                    std::ptr::null()
                } else {
                    descriptor().map_or(std::ptr::null(), |descriptor| descriptor as *const _)
                }
            }

            unsafe extern "C" fn entry_init(_path: *const c_char) -> bool {
                descriptor().is_some()
            }
            unsafe extern "C" fn entry_deinit() {}
            unsafe extern "C" fn entry_get_factory(factory_id: *const c_char) -> *const c_void {
                if factory_id.is_null() {
                    return std::ptr::null();
                }
                let id = unsafe { CStr::from_ptr(factory_id) };
                let expected = unsafe {
                    CStr::from_ptr(
                        $crate::clap_sys::factory::plugin_factory::CLAP_PLUGIN_FACTORY_ID.as_ptr()
                            as *const c_char,
                    )
                };
                if id == expected {
                    return &FACTORY.0 as *const _ as *const c_void;
                }
                std::ptr::null()
            }

            #[unsafe(no_mangle)]
            pub static clap_entry: $crate::clap_sys::entry::clap_plugin_entry_t =
                $crate::clap_sys::entry::clap_plugin_entry_t {
                    clap_version: $crate::CLAP_VERSION,
                    init: Some(entry_init),
                    deinit: Some(entry_deinit),
                    get_factory: Some(entry_get_factory),
                };
        }
    };
}

// C-ABI shim (boilerplate to forward C calls to Rust Trait)
// This is usually hidden behind a macro
#[macro_export]
macro_rules! export_clap_plugin {
    ($plugin_type:ty, $plugin_info:expr, $features:expr) => {
        $crate::__export_clap_plugin_impl!($plugin_type, $plugin_info, $features, PluginEntry);
    };
}

/// Export macro for plugins with GUI support
/// Requires the plugin to implement both Plugin and GuiHandler traits
#[macro_export]
macro_rules! export_clap_plugin_with_gui {
    ($plugin_type:ty, $plugin_info:expr, $features:expr) => {
        $crate::__export_clap_plugin_impl!(
            $plugin_type,
            $plugin_info,
            $features,
            PluginEntryWithGui
        );
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap_sys::events::clap_output_events_t;
    use clap_sys::ext::gui::clap_host_gui_t;
    use clap_sys::ext::params::clap_host_params_t;
    use std::ffi::{CStr, c_char, c_void};

    struct ExportTestPlugin;

    impl Plugin for ExportTestPlugin {
        type AudioProcessor = ();

        fn new(_host: HostHandle) -> Self {
            Self
        }

        fn activate(
            &mut self,
            _sample_rate: f64,
            _min_frames: u32,
            _max_frames: u32,
        ) -> Option<Self::AudioProcessor> {
            Some(())
        }

        fn get_parameter(&self, _id: u32) -> f64 {
            0.0
        }

        fn set_parameter(&mut self, _id: u32, _value: f64) {}
    }

    struct SyncFeatures([*const c_char; 2]);
    unsafe impl Sync for SyncFeatures {}

    static FEATURES: SyncFeatures = SyncFeatures([
        b"audio-effect\0".as_ptr() as *const c_char,
        std::ptr::null(),
    ]);

    crate::export_clap_plugin!(
        ExportTestPlugin,
        PluginInfo {
            id: "com.sunmao.clap-rs.export-test",
            name: "CLAP Rust Export Test",
            vendor: "SunMao",
            url: "https://example.test",
            manual_url: "",
            support_url: "",
            version: "1.0.0",
            description: "Plain Rust metadata strings",
        },
        FEATURES.0
    );

    fn plugin_info() -> PluginInfo {
        PluginInfo {
            id: "com.sunmao.clap-rs.test",
            name: "CLAP Rust Test",
            vendor: "SunMao",
            url: "https://example.test",
            manual_url: "https://example.test/manual",
            support_url: "https://example.test/support",
            version: "1.2.3",
            description: "Descriptor without caller-provided terminators",
        }
    }

    #[test]
    fn descriptor_owns_nul_terminated_copies_of_plain_rust_strings() {
        let descriptor =
            OwnedPluginDescriptor::new(&plugin_info(), std::ptr::null()).expect("valid metadata");
        let raw = descriptor.as_raw();

        let fields = [
            (raw.id, "com.sunmao.clap-rs.test"),
            (raw.name, "CLAP Rust Test"),
            (raw.vendor, "SunMao"),
            (raw.url, "https://example.test"),
            (raw.manual_url, "https://example.test/manual"),
            (raw.support_url, "https://example.test/support"),
            (raw.version, "1.2.3"),
            (
                raw.description,
                "Descriptor without caller-provided terminators",
            ),
        ];

        for (pointer, expected) in fields {
            assert_eq!(unsafe { CStr::from_ptr(pointer) }.to_str(), Ok(expected));
        }
    }

    #[test]
    fn export_macro_publishes_plain_rust_strings_as_c_metadata() {
        let entry = &__clap_rs_impl::clap_entry;
        assert!(unsafe { entry.init.expect("entry init")(std::ptr::null()) });

        let factory = unsafe {
            entry.get_factory.expect("factory lookup")(
                clap_sys::factory::plugin_factory::CLAP_PLUGIN_FACTORY_ID.as_ptr() as *const c_char,
            ) as *const clap_sys::factory::plugin_factory::clap_plugin_factory_t
        };
        assert!(!factory.is_null());

        let descriptor = unsafe {
            (*factory)
                .get_plugin_descriptor
                .expect("descriptor callback")(factory, 0)
        };
        assert!(!descriptor.is_null());
        assert_eq!(
            unsafe { CStr::from_ptr((*descriptor).id) }.to_bytes(),
            b"com.sunmao.clap-rs.export-test"
        );
        assert_eq!(
            unsafe { CStr::from_ptr((*descriptor).description) }.to_bytes(),
            b"Plain Rust metadata strings"
        );
    }

    #[test]
    fn descriptor_accepts_one_legacy_trailing_nul() {
        let mut info = plugin_info();
        info.id = "com.sunmao.legacy\0";
        let descriptor =
            OwnedPluginDescriptor::new(&info, std::ptr::null()).expect("legacy metadata");

        assert_eq!(
            unsafe { CStr::from_ptr(descriptor.as_raw().id) }.to_bytes(),
            b"com.sunmao.legacy"
        );
    }

    #[test]
    fn descriptor_rejects_interior_nul_bytes() {
        let mut info = plugin_info();
        info.name = "invalid\0name";

        assert!(matches!(
            OwnedPluginDescriptor::new(&info, std::ptr::null()),
            Err("name")
        ));
    }

    #[derive(Default)]
    struct TestHostState {
        expose_params: bool,
        expose_gui: bool,
        flush_requests: usize,
        resize_requests: Vec<(u32, u32)>,
        resize_result: bool,
    }

    unsafe extern "C" fn test_host_get_extension(
        host: *const clap_host_t,
        extension_id: *const c_char,
    ) -> *const c_void {
        if host.is_null() || extension_id.is_null() {
            return std::ptr::null();
        }
        let state = unsafe { &*((*host).host_data as *const TestHostState) };
        match unsafe { CStr::from_ptr(extension_id) }.to_bytes() {
            b"clap.params" if state.expose_params => {
                (&TEST_HOST_PARAMS as *const clap_host_params_t).cast()
            }
            b"clap.gui" if state.expose_gui => (&TEST_HOST_GUI as *const clap_host_gui_t).cast(),
            _ => std::ptr::null(),
        }
    }

    unsafe extern "C" fn test_host_request_flush(host: *const clap_host_t) {
        let state = unsafe { &mut *((*host).host_data as *mut TestHostState) };
        state.flush_requests += 1;
    }

    unsafe extern "C" fn test_host_request_resize(
        host: *const clap_host_t,
        width: u32,
        height: u32,
    ) -> bool {
        let state = unsafe { &mut *((*host).host_data as *mut TestHostState) };
        state.resize_requests.push((width, height));
        state.resize_result
    }

    static TEST_HOST_PARAMS: clap_host_params_t = clap_host_params_t {
        rescan: None,
        clear: None,
        request_flush: Some(test_host_request_flush),
    };

    static TEST_HOST_GUI: clap_host_gui_t = clap_host_gui_t {
        resize_hints_changed: None,
        request_resize: Some(test_host_request_resize),
        request_show: None,
        request_hide: None,
        closed: None,
    };

    fn test_host(state: &mut TestHostState) -> clap_host_t {
        clap_host_t {
            clap_version: CLAP_VERSION,
            host_data: (state as *mut TestHostState).cast(),
            name: std::ptr::null(),
            vendor: std::ptr::null(),
            url: std::ptr::null(),
            version: std::ptr::null(),
            get_extension: Some(test_host_get_extension),
            request_restart: None,
            request_process: None,
            request_callback: None,
        }
    }

    #[derive(Debug, PartialEq)]
    enum TestOutputEvent {
        Begin(u32),
        Value(u32, f64),
        End(u32),
    }

    struct TestOutputEvents {
        accept: bool,
        events: Vec<TestOutputEvent>,
    }

    unsafe extern "C" fn test_output_try_push(
        list: *const clap_output_events_t,
        header: *const clap_event_header_t,
    ) -> bool {
        let output = unsafe { &mut *((*list).ctx as *mut TestOutputEvents) };
        if !output.accept {
            return false;
        }
        let event = match unsafe { (*header).type_ } {
            CLAP_EVENT_PARAM_GESTURE_BEGIN => {
                let event = unsafe { &*(header as *const clap_event_param_gesture_t) };
                TestOutputEvent::Begin(event.param_id)
            }
            CLAP_EVENT_PARAM_VALUE => {
                let event = unsafe { &*(header as *const clap_event_param_value_t) };
                TestOutputEvent::Value(event.param_id, event.value)
            }
            CLAP_EVENT_PARAM_GESTURE_END => {
                let event = unsafe { &*(header as *const clap_event_param_gesture_t) };
                TestOutputEvent::End(event.param_id)
            }
            event_type => panic!("unexpected output event type {event_type}"),
        };
        output.events.push(event);
        true
    }

    fn test_output(output: &mut TestOutputEvents) -> clap_output_events_t {
        clap_output_events_t {
            ctx: (output as *mut TestOutputEvents).cast(),
            try_push: Some(test_output_try_push),
        }
    }

    #[test]
    fn host_handle_queues_parameter_gestures_and_values_in_order() {
        let mut state = TestHostState {
            expose_params: true,
            ..TestHostState::default()
        };
        let host = test_host(&mut state);
        let handle = unsafe { HostHandle::from_raw(&host) };

        assert!(handle.begin_edit(17));
        assert!(handle.perform_edit(17, 0.625));
        assert!(handle.end_edit(17));
        assert_eq!(state.flush_requests, 3);

        let mut output = TestOutputEvents {
            accept: true,
            events: Vec::new(),
        };
        let output_list = test_output(&mut output);
        assert_eq!(unsafe { handle.flush_parameter_events(&output_list) }, 3);
        assert_eq!(
            output.events,
            vec![
                TestOutputEvent::Begin(17),
                TestOutputEvent::Value(17, 0.625),
                TestOutputEvent::End(17),
            ]
        );
        assert_eq!(unsafe { handle.flush_parameter_events(&output_list) }, 0);
    }

    #[test]
    fn rejected_parameter_output_remains_queued_for_retry() {
        let mut state = TestHostState {
            expose_params: true,
            ..TestHostState::default()
        };
        let host = test_host(&mut state);
        let handle = unsafe { HostHandle::from_raw(&host) };
        assert!(handle.perform_edit(9, 0.25));

        let mut output = TestOutputEvents {
            accept: false,
            events: Vec::new(),
        };
        let mut output_list = test_output(&mut output);
        assert_eq!(unsafe { handle.flush_parameter_events(&output_list) }, 0);
        assert!(output.events.is_empty());

        output.accept = true;
        output_list = test_output(&mut output);
        assert_eq!(unsafe { handle.flush_parameter_events(&output_list) }, 1);
        assert_eq!(output.events, vec![TestOutputEvent::Value(9, 0.25)]);
    }

    #[test]
    fn host_handle_rejects_non_finite_values_and_missing_extensions() {
        let mut state = TestHostState::default();
        let host = test_host(&mut state);
        let handle = unsafe { HostHandle::from_raw(&host) };

        assert!(!handle.begin_edit(1));
        assert!(!handle.perform_edit(1, 0.5));
        assert!(!handle.end_edit(1));
        assert!(!handle.request_resize(640, 480));

        state.expose_params = true;
        assert!(!handle.perform_edit(1, f64::NAN));
        assert_eq!(state.flush_requests, 0);
    }

    #[test]
    fn host_handle_forwards_editor_resize_requests_and_results() {
        let mut state = TestHostState {
            expose_gui: true,
            resize_result: true,
            ..TestHostState::default()
        };
        let host = test_host(&mut state);
        let handle = unsafe { HostHandle::from_raw(&host) };

        assert!(handle.request_resize(960, 540));
        state.resize_result = false;
        assert!(!handle.request_resize(1280, 720));
        assert_eq!(state.resize_requests, vec![(960, 540), (1280, 720)]);
    }
}
