[package]
name = "sunmao_fx_gain_gui_wgpu"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sunmao_fx_gain_gui_wgpu_standalone"
path = "src/bin/standalone.rs"
required-features = ["standalone"]

[features]
default = []
au = ["dep:sunmao_backend_au"]
standalone = ["sunmao/standalone"]

[dependencies]
sunmao = { path = "../../sunmao", features = ["gui-wgpu"] }

[target.'cfg(target_os = "macos")'.dependencies]
sunmao_backend_au = { path = "../../sunmao/backend_au", optional = true }
