[package]
name = "sunmao_syn_sine_gui_webview"
version = "0.1.0"
edition = "2021"
description = "Sine synth example with a WebView GUI using SunMao"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "sunmao_syn_sine_gui_webview_standalone"
path = "src/bin/standalone.rs"
required-features = ["standalone"]

[features]
default = []
standalone = ["sunmao/standalone"]

[dependencies]
sunmao = { path = "../../sunmao", features = ["gui-webview"] }
