[package]
name = "sunmao_daw_info_gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
sunmao_core = { path = "../../sunmao/core" }
sunmao_macros = { path = "../../sunmao/macros" }
sunmao_gui = { path = "../../sunmao/gui", features = ["gl"] }
sunmao_view_baseview = { path = "../../sunmao/view_baseview" }
sunmao_backend_vst3 = { path = "../../sunmao/backend_vst3" }
sunmao_backend_au = { path = "../../sunmao/backend_au" }
sunmao_backend_clap = { path = "../../sunmao/backend_clap" }
