[package]
name = "sunmao_daw_info_gui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[features]
default = []
au = ["dep:sunmao_backend_au"]

[dependencies]
sunmao = { path = "../../sunmao", features = ["gui-gl"] }

[target.'cfg(target_os = "macos")'.dependencies]
sunmao_backend_au = { path = "../../sunmao/backend_au", optional = true }
